_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/binary
PREPROCESS:
  OVERWRITE: False
  DISABLE_CHECK: False
  OUTPUT: [["image", "png"], ["binary_seg", "npy"]]

  RESIZE:
    RESIZE_MODE: "scaling"
    SCALING: 0.5
    MAX_SIZE: -1

  REGION:
    REGIONS:
      [
        "marginalia",
        "page-number",
        "resolution",
        "date",
        "index",
        "attendance",
        "Resumption",
        "resumption",
        "Insertion",
        "insertion",
      ]
    MERGE_REGIONS: ["resolution:Resumption,resumption,Insertion,insertion"]
    REGION_TYPE: []
  BASELINE:
    LINE_WIDTH: 10

INPUT:
  RESIZE_MODE: "scaling"
  SCALING_TRAIN: 1.0
  MAX_SIZE_TRAIN: -1

  MAX_SIZE_TEST: -1

  CROP:
    ENABLED: True
    SIZE: [2048, 2048]
    TYPE: absolute

  FORMAT: RGB

  GRAYSCALE:
    PROBABILITY: 0.1

  BRIGHTNESS:
    PROBABILITY: 0.2
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  CONTRAST:
    PROBABILITY: 0.2
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  SATURATION:
    PROBABILITY: 0.1
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  GAUSSIAN_FILTER:
    PROBABILITY: 0.2
    MIN_SIGMA: 0.5
    MAX_SIGMA: 1.5

  HORIZONTAL_FLIP:
    PROBABILITY: 0.

  VERTICAL_FLIP:
    PROBABILITY: 0.

  ELASTIC_DEFORMATION:
    PROBABILITY: 0.2
    ALPHA: 0.1
    SIGMA: 0.01

  AFFINE:
    PROBABILITY: 1.

    TRANSLATION:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.02

    ROTATION:
      PROBABILITY: 0.9
      KAPPA: 30.

    SHEAR:
      PROBABILITY: 0.9
      KAPPA: 20.

    SCALE:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.12

  ORIENTATION:
    PROBABILITY: 1.0
    PERCENTAGES: (0.25, 0.25, 0.25, 0.25)

DATALOADER:
  NUM_WORKERS: 8
  FILTER_EMPTY_ANNOTATIONS: False

SOLVER:
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 25000
  BASE_LR: 0.0002
  GAMMA: 0.1
  STEPS: () #(80000, 120000, 160000)
  MAX_ITER: 250000

MODEL:
  META_ARCHITECTURE: "BinarySegmentor"
  MODE: region
  AMP_TRAIN:
    ENABLED: True

  BINARY_SEG_HEAD:
    NUM_CLASSES: 6

  WEIGHTS:

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
  EVAL_PERIOD: 10000
