_BASE_: ./segmentation/baseline/baseline_general.yaml

OUTPUT_DIR: ./output/region

NAME: region_baseline_test

PREPROCESS:
  OVERWRITE: False
  DISABLE_CHECK: False

  RESIZE:
    RESIZE_MODE: "scaling"
    SCALING: 0.5
    MAX_SIZE: -1

  REGION:
    REGIONS:
      [
        "Name",
        "Award",
        "Birth Place",
        "Birth Date",
        "Father",
        "Mother",
        "Religion",
        "Marriage Location",
        "Spouse",
        "Children",
        "Rank",
        "Ship",
        "Departure",
        "Death Date",
        "Death Place",
        "Retirement",
        "Repatriation",
        None
      ]
    MERGE_REGIONS: None
    REGION_TYPE: []
  BASELINE:
    LINE_WIDTH: 10

INPUT:
  RESIZE_MODE: "scaling"
  SCALING_TRAIN: 1.0
  MAX_SIZE_TRAIN: -1

  MAX_SIZE_TEST: -1

  CROP:
    ENABLED: False
    SIZE: [1024, 1024]
    TYPE: absolute

  FORMAT: RGB

  GRAYSCALE:
    PROBABILITY: 0.1

  BRIGHTNESS:
    PROBABILITY: 0.2
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  CONTRAST:
    PROBABILITY: 0.2
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  SATURATION:
    PROBABILITY: 0.1
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  GAUSSIAN_FILTER:
    PROBABILITY: 0.2
    MIN_SIGMA: 0.5
    MAX_SIGMA: 1.5

  HORIZONTAL_FLIP:
    PROBABILITY: 0.

  VERTICAL_FLIP:
    PROBABILITY: 0.

  ELASTIC_DEFORMATION:
    PROBABILITY: 0.2
    ALPHA: 0.1
    SIGMA: 0.01

  AFFINE:
    PROBABILITY: 1.

    TRANSLATION:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.02

    ROTATION:
      PROBABILITY: 0.9
      KAPPA: 30.

    SHEAR:
      PROBABILITY: 0.9
      KAPPA: 20.

    SCALE:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.12

  ORIENTATION:
    PROBABILITY: 1.0
    PERCENTAGES: (0.25, 0.25, 0.25, 0.25)

DATALOADER:
  NUM_WORKERS: 0
  FILTER_EMPTY_ANNOTATIONS: False

SOLVER:
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 2000
  BASE_LR: 0.0002
  GAMMA: 0.1
  STEPS: () #(80000, 120000, 160000)
  MAX_ITER: 250000

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 19

  WEIGHTS:

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
  EVAL_PERIOD: 10000
